---

- name: install python3-cryptography
  apt:
    force_apt_get: yes
    update_cache: yes
    name: python3-cryptography

- name: generate openssl certifcate
  openssl_certificate:
      path: /tmp/ansible.gen.crt
      privatekey_path: /tmp/ansible.gen.key
      csr_path: /tmp/ansible.gen.csr
      provider: selfsigned

...
