---


- name: "copy systemd settings"
  ansible.builtin.copy:
    src: "{{ item }}"
    dest: "/etc/systemd/{{ item }}"
    owner: "root"
    group: "root"
    mode: "0644"
  loop:
    - "sleep.conf"


...
