---

- hosts: localhost
  roles:
    - { name: manage_packages, become: yes }
    - { name: disable_services, become: yes }
    - { name: gpg_setup }
    - { name: configure_vim }
    - { name: configure_firefox }
    - { name: install_docker_ce, become: yes }

...
