---

- hosts: all

  roles:
    - { name: configure_apt, become: yes, tags: [configure_apt] }
    - { name: manage_packages, become: yes, tags: [manage_packages] }
    - { name: gpg_setup, tags: [gpg,gnupg] }
    - { name: nitrokey_app, become: yes, tags: [nitrokey_app] }
    - { name: configure_vim, tags: [configure_vim] }
    - { name: configure_bashrc, tags: [configure_bashrc] }
    - { name: configure_git, tags: [configure_git] }

    - { name: configure_firewall, become: yes, tags: [firewall] }
    - { name: install_firefox, become: yes, tags: [install_firefox] }
    - { name: configure_firefox, tags: [configure_firefox] }
    - { name: install_tor, become: yes, tags: [tor] }
    - { name: install_brave, become: yes, tags: [brave] }
    - { name: install_yaru_theme, become: yes, tags: [yaru] }
    - { name: configure_abcde, tags: [abcde] }
    - { name: install_protonvpn, become: yes, tags: [protonvpn] }
    - { name: configure_cmdline_linux, become: yes, tags: [cmdline_linux] }
    - { name: node_exporter, become: yes, tags: [node_exporter] }

  # Clear downloaded .deb packages.
  # Currently Ansible does not support this in a module.
  handlers:
      - name: "apt_get_clean"
        become: "yes"
        command: "apt-get clean"
        args:
            warn: False

  # nVidia notes.
  # nvidia-driver installation is interactive, also a subject
  # to change. nVidia drivers installation is manual.
  # Install last.
  #
  # nvidia-driver
  # nvidia-smi
  # bumblebee-nvidia
  # primus-nvidia
  # primus-vk-nvidia
  # bbswitch

...
