---

- hosts: localhost
  roles:
    - { name: manage_packages, become: yes, tags: [apt] }
    - { name: configure_apt, become: yes, tags: [confapt] }
    - { name: disable_services, become: yes, tags: [systemd] }
    - { name: gpg_setup, tags: [gpg,gnupg] }
    - { name: configure_vim, tags: [vim] }
    - { name: configure_git, tags: [git] }
    - { name: configure_firewall, become: yes, tags: [firewall] }
    - { name: configure_firefox, tags: [firefox] }
    - { name: install_brave, become: yes, tags: [brave] }
    - { name: configure_abcde, tags: [abcde] }
    - { name: clone_protonvpn_cli, become: yes, tags: [protonvpn] }

...
