---


# https://github.com/signalapp/Signal-Desktop/issues/4761
# https://github.com/electron/electron/issues/27527


- name: "add Signal repository key"
  ansible.builtin.apt_key:
    url: "https://updates.signal.org/desktop/apt/keys.asc"
    state: "present"


- name: "add Signal repository"
  ansible.builtin.apt_repository:
    repo: "deb [arch=amd64] https://updates.signal.org/desktop/apt xenial main"
    state: "present"


- name: "install Signal Desktop"
  ansible.builtin.apt:
    force_apt_get: "yes"
    update_cache: "yes"
    name: "signal-desktop"
    state: "latest"
  notify:
    - "apt_get_clean"


...
