---

# --CreateProfile does not modify the existing prefs.js
# It is safe to run muliple times.
- name: "create dedicated profiles"
  shell: "{{ firefox_dir }}/firefox --no-remote --CreateProfile '{{ item }} {{ profiles_dir }}/{{ item }}'"
  loop: "{{ profiles }}"


# Create and append aliases
- name: "create and append aliases"
  lineinfile:
    path: "{{ ansible_env.HOME }}/.bash_aliases"
    create: "yes"
    insertafter: "EOF"
    line: "alias firefox-{{ item }}='{{ firefox_dir }}/firefox --no-remote --profile {{ profiles_dir }}/{{ item }}'"
  loop: "{{ profiles }}"


- name: "create launchers directory"
  file:
    path: "{{ firefox_launchers_dir }}"
    state: "directory"
    owner: "{{ ansible_env.USER }}"
    group: "{{ ansible_env.USER }}"
    mode: "0750"


- name: "create launchers for all profiles"
  copy:
    content: |
      #!/usr/bin/env bash

      {{ firefox_dir }}/firefox --no-remote --profile {{ profiles_dir }}/{{ item }}
    dest: "{{ firefox_launchers_dir }}/firefox.{{ item }}.sh"
    mode: "0750"
  loop: "{{ profiles }}"


- name: "create local desktop entries directory"
  become: "yes"
  file:
    path: "/usr/local/share/applications"
    state: "directory"
    owner: "root"
    group: "root"
    mode: "0755"


- name: "create desktop entries for all profiles"
  become: "yes"
  template:
    src: "kmwil.firefox.desktop"
    dest: "/usr/local/share/applications/kmwil.firefox.{{ item }}.desktop"
    owner: "root"
    group: "root"
    mode: "0644"
  loop: "{{ profiles }}"

...
