---


# --CreateProfile does not modify the existing prefs.js
# It is safe to run muliple times.
- name: "create dedicated profiles"
  shell: "{{ firefox_dir }}/firefox --no-remote --CreateProfile '{{ item.name }} {{ firefox_profiles_dir }}/{{ item.name }}'"
  loop: "{{ firefox_profiles }}"
  when: item.status == "present"


- name: "remove deleted profiles directories"
  ansible.builtin.file:
    path: "{{ firefox_profiles_dir }}/{{ item.name }}"
    state: "absent"
  loop: "{{ firefox_profiles }}"
  when: item.status == "absent"


# Create and append aliases.
- name: "create and append aliases"
  ansible.builtin.lineinfile:
    path: "{{ ansible_env.HOME }}/.bash_aliases"
    create: "yes"
    insertafter: "EOF"
    line: "alias firefox-{{ item.name }}='{{ firefox_dir }}/firefox --no-remote --profile {{ firefox_profiles_dir }}/{{ item.name }}'"
  loop: "{{ firefox_profiles }}"
  when: item.status == "present"


# Remove aliases.
- name: "remove aliases"
  ansible.builtin.lineinfile:
    path: "{{ ansible_env.HOME }}/.bash_aliases"
    line: "alias firefox-{{ item.name }}='{{ firefox_dir }}/firefox --no-remote --profile {{ firefox_profiles_dir }}/{{ item.name }}'"
    state: "absent"
  loop: "{{ firefox_profiles }}"
  when: item.status == "absent"


- name: "create local desktop entries directory"
  become: "yes"
  file:
    path: "/usr/local/share/applications"
    state: "directory"
    owner: "root"
    group: "root"
    mode: "0755"


- name: "create desktop entries"
  become: "yes"
  template:
    src: "kamil.firefox.desktop"
    dest: "/usr/local/share/applications/kamil.firefox.{{ item.name }}.desktop"
    owner: "root"
    group: "root"
    mode: "0644"
  loop: "{{ firefox_profiles }}"
  when: item.status == "present"


- name: "remove desktop entries"
  become: "yes"
  file:
    path: "/usr/local/share/applications/kamil.firefox.{{ item.name }}.desktop"
    state: "absent"
  loop: "{{ firefox_profiles }}"
  when: item.status == "absent"


- name: "update profiles list"
  template:
    src: "profiles.ini"
    dest: "{{ ansible_env.HOME }}/.mozilla/firefox/profiles.ini"
    mode: "0644"
  loop: "{{ firefox_profiles }}"

...
