---

- name: install required packages
  apt:
    force_apt_get: yes
    update_cache: yes
    name: "{{ item.name }}"
    state: present
  with_items: "{{ packages }}"

- name: add Docker repository key
  apt_key:
    url: https://download.docker.com/linux/debian/gpg
    state: present
  when: ansible_distribution == "Debian"

- name: add Docker repository
  apt_repository:
    repo: >
      deb [arch=amd64] https://download.docker.com/linux/debian
      {{ ansible_distribution_release }} stable
    state: present

- name: install latest Docker CE
  apt:
    force_apt_get: yes
    update_cache: yes
    name: docker-ce
    state: latest

# For some reason logging out was not enough to reset group
# membership. I had to reboot the machine.
- name: add {{ ansible_env.USER }} to the docker group
  user:
    name: "{{ ansible_env.USER }}"
    append: yes
    groups: docker
    state: present
