" Editor settings.
set tabstop=2
set softtabstop=2
set shiftwidth=2
set expandtab

" Get rid of ~ files.
set nobackup

" 256 colors in VIm.
set t_Co=256

" Status line
set laststatus=2

" Nice colorscheme.
" https://github.com/Lokaltog/vim-distinguished
colorscheme distinguished

" Turn off old stuff.
set nocompatible

" Automatic indentation based on filetype and contents.
filetype plugin indent on

" Syntax higlighting.
syntax on

" Skeleton file for C++.
" au BufNewFile *.cc 0r ~/.vim/cc.skel

" Specific syntax higlighting for Cisco configuration.
autocmd BufRead,BufNewFile *.ios set syntax=ios
autocmd BufRead,BufNewFile *.dhcpd.conf set syntax=dhcpd
autocmd BufRead,BufNewFile *.zone set syntax=bindzone

function GetMode()
	if mode() == "i"
		return "INSERT"
	elseif mode() == "n"
		return "NORMAL"
	elseif mode() == "v"
		return "VISUAL CHAR"
	elseif mode() == "V"
		return "VISUAL LINE"
	elseif mode() == "^V"
		return "VISUAL BLOCK"
	elseif mode() == "c"
		return "COMMAND LINE"
	else
		return "OTHER"
	endif
endfunction

hi User1 ctermfg=white ctermbg=235
hi User5 ctermfg=black ctermbg=190
hi User4 ctermfg=black ctermbg=233
hi User2 ctermfg=black ctermbg=190 cterm=bold

set statusline=
set statusline+=%2*\ %{GetMode()}\ %5*\ [%t][%M]\ %4*
set statusline+=%=
set statusline+=%1*\ %y\ %*
set statusline+=%5*\ %p%%\ \ L%l\ \ C%v\ %*

" Short text width.
" set textwidth=76
" highlight ColorColumn ctermbg=234
" set colorcolumn=+1
