" Editor settings.
set tabstop=4
set softtabstop=4
set shiftwidth=4
set expandtab

" Get rid of ~ files.
set nobackup

" 256 colors in VIm.
set t_Co=256

" Status line
set laststatus=2

" Nice colorscheme.
" https://github.com/Lokaltog/vim-distinguished
" colorscheme distinguished
" gruvbox
" https://github.com/morhetz/gruvbox.git
let g:gruvbox_contrast_dark = 'hard'
set background=dark
colorscheme gruvbox

" Turn off old stuff.
set nocompatible

" Automatic indentation based on filetype and contents.
filetype plugin indent on

" Syntax higlighting.
syntax on

" Skeleton files.
autocmd BufNewFile *.bash,*.sh 0r ~/.vim/templates/bash.bash

" Specific syntax higlighting for Cisco configuration.
autocmd BufRead,BufNewFile *.ios set syntax=ios
autocmd BufRead,BufNewFile *.j2 set syntax=jinja
autocmd BufRead,BufNewFile *.dhcpd.conf set syntax=dhcpd
autocmd BufRead,BufNewFile *.zone set syntax=bindzone

function GetMode()
	if mode() == "i"
		return "INSERT"
	elseif mode() == "n"
		return "NORMAL"
	elseif mode() == "v"
		return "VISUAL CHAR"
	elseif mode() == "V"
		return "VISUAL LINE"
	elseif mode() == "^V"
		return "VISUAL BLOCK"
	elseif mode() == "c"
		return "COMMAND LINE"
	else
		return "OTHER"
	endif
endfunction

" hi User1 ctermfg=white ctermbg=235
" hi User5 ctermfg=black ctermbg=190
" hi User4 ctermfg=black ctermbg=233
" hi User2 ctermfg=black ctermbg=190 cterm=bold
hi Normal ctermbg=None

set statusline=
set statusline+=%2*\ %{GetMode()}\ %5*\ [%t][%M]\ %4*
set statusline+=%=
set statusline+=%1*\ %y\ %*
set statusline+=%5*\ %p%%\ \ L%l\ \ C%v\ %*
