---

- name: "create group for the node_exporter"
  group:
    gid: "{{ node_exporter_user_uid_gid }}"
    name: "{{ node_exporter_user }}"
    state: "present"

- name: "create user for the node_exporter"
  user:
    comment: "Node Exporter"
    group: "{{ node_exporter_user }}"
    state: "present"
    name: "{{ node_exporter_user }}"
    uid: "{{ node_exporter_user_uid_gid }}"
    create_home: "yes"
    shell: "/sbin/nologin"

- name: "remove previous installation"
  file:
    path: "{{ node_exporter_dir }}"
    state: "absent"

- name: "create node_exporter directories"
  file:
    path: "{{ node_exporter_dir }}"
    state: "directory"
    owner: "{{ node_exporter_user }}"
    group: "{{ node_exporter_user }}"
    mode: "0755"

- name: "download node_exporter"
  unarchive:
    src: "{{ node_exporter_url }}"
    dest: "{{ node_exporter_dir }}"
    remote_src: "yes"
    owner: "{{ node_exporter_user }}"
    group: "{{ node_exporter_user }}"
    extra_opts:
      - "--strip-components=1"

- name: "copy systemd service"
  template:
    src: "{{ node_exporter_service }}.j2"
    dest: "/etc/systemd/system/{{ node_exporter_service }}"
    owner: "root"
    group: "root"
    mode: "0644"

- name: "copy node_exporter configuration file"
  template:
    src: "{{ node_exporter_config }}.j2"
    dest: "/etc/{{ node_exporter_config }}"
    owner: "root"
    group: "root"
    mode: "0644"

- name: "start and enable node_exporter"
  systemd:
    name: "{{ node_exporter_service }}"
    state: "restarted"
    enabled: "yes"

...
