---


- name: "remove previous Firefox installation"
  ansible.builtin.file:
    path: "{{ firefox_dir }}"
    state: "absent"


- name: "create Firefox install directory"
  ansible.builtin.file:
    path: "{{ firefox_dir }}"
    state: "directory"
    owner: "{{ ansible_env.USER }}"
    group: "{{ ansible_env.USER }}"
    mode: "0750"


- name: "install Firefox"
  ansible.builtin.unarchive:
    remote_src: "yes"
    src: "{{ firefox_url }}"
    dest: "{{ firefox_dir }}"
    owner: "{{ ansible_env.USER }}"
    group: "{{ ansible_env.USER }}"
    extra_opts:
      - "--strip-components=1"


- name: "change ownership of all files"
  ansible.builtin.file:
    path: "{{ firefox_dir }}"
    state: "directory"
    recurse: "yes"
    owner: "{{ ansible_env.USER }}"
    group: "{{ ansible_env.USER }}"


...
