---

- name: remove unwanted packages
  apt:
    force_apt_get: yes
    update_cache: yes
    name: "{{ unwanted_packages }}"
    state: absent
    purge: yes
    autoremove: yes

- name: install packages
  apt:
    install_recommends: no
    force_apt_get: yes
    update_cache: yes
    name: "{{ item }}"
    state: present
  loop:
    - "{{ texlive }}"
    - "{{ packages }}"

...
