---


- name: "remove unwanted packages"
  ansible.builtin.apt:
    force_apt_get: "yes"
    update_cache: "yes"
    name: "{{ unwanted_packages }}"
    state: "absent"
    purge: "yes"
    autoremove: "yes"


- name: "install packages"
  ansible.builtin.apt:
    install_recommends: "no"
    force_apt_get: "yes"
    update_cache: "yes"
    name: "{{ item }}"
    state: "present"
  loop: "{{ packages }}"
  notify:
    - "apt_get_clean"


...
