---

- name: remove unwanted packages
  apt:
    force_apt_get: yes
    update_cache: yes
    name: "{{ unwanted_packages }}"
    state: absent
    purge: yes
    autoremove: yes

- name: install packages
  apt:
    install_recommends: no
    force_apt_get: yes
    update_cache: yes
    name: "{{ item }}"
    state: present
  loop:
    - "{{ texlive }}"
    - "{{ packages }}"

- name: install hardware-related packages
  apt:
    install_recommends: no
    force_apt_get: yes
    update_cache: yes
    name: "{{ hardware_e480 }}"
    state: present
  when:
    - ansible_product_version == "ThinkPad E480"

...
