---

- name: remove unwanted packages
  apt:
    force_apt_get: yes
    update_cache: yes
    name: "{{ item.name }}"
    state: absent
    purge: yes
    autoremove: yes
  with_items: "{{ unwanted_packages }}"

- name: install packages
  apt:
    install_recommends: no
    force_apt_get: yes
    update_cache: yes
    name: "{{ item.name }}"
    state: latest
  with_items: "{{ packages }}"

...
