global:
  scrape_interval:     30s
  evaluation_interval: 30s

# scrape_configs zawiera definicje zadań (ang. job), czyli opis
# pobierania metryk. Każdy job_name stanowi jedno zadanie; Prometeusz
# automatycznie dodaje do każdej metryki dwie etykiety (ang. label):
# instance      Do którego hosta należy metryka.
# job           Do którego zadania należy metryka.
scrape_configs:

  - job_name: 'node_exporter'
    static_configs:
        - targets:
            - 'localhost:9100'
  
  - job_name: 'prometheus'
    static_configs:
        - targets:
            - 'localhost:9090'
