---

- name: create group for the prometheus
  group:
    gid: "{{ prometheus_user_uid_gid }}"
    name: "{{ prometheus_user }}"
    state: "present"

- name: create user for the prometheus
  user:
    comment: "Prometheus"
    group: "{{ prometheus_user }}"
    state: "present"
    name: "{{ prometheus_user }}"
    uid: "{{ prometheus_user_uid_gid }}"
    create_home: yes
    shell: "/sbin/nologin"

- name: remove previous installation
  file:
    path: "{{ node_exporter_dir }}"
    state: absent

- name: create {{ prometheus_dir }}
  file:
      path: "{{ prometheus_dir }}"
      state: directory
      owner: "{{ prometheus_user }}"
      group: "{{ prometheus_user }}"
      mode: 0755

- name: create prometheus_tsdb dir
  file:
    path: "{{ prometheus_tsdb }}"
    state: directory
    owner: "{{ prometheus_user }}"
    group: "{{ prometheus_user }}"
    mode: 0755

- name: download prometheus
  unarchive:
      src: "{{ prometheus_url }}"
      dest: "{{ prometheus_dir }}"
      remote_src: yes
      owner: "{{ prometheus_user }}"
      group: "{{ prometheus_user }}"
      extra_opts:
          - --strip-components=1

- name: copy systemd service
  template:
      src: "{{ prometheus_service }}.j2"
      dest: "/etc/systemd/system/{{ prometheus_service }}"
      owner: root
      group: root
      mode: 0644

- name: copy prometheus.yml configuration file
  copy:
      src: "{{ prometheus_config }}"
      dest: "{{ prometheus_dir }}/{{ prometheus_config }}"
      owner: "{{ prometheus_user }}"
      group: "{{ prometheus_user }}"
      mode: 0644

- name: start and enable prometheus
  systemd:
      name: "{{ prometheus_service }}"
      state: restarted
      enabled: yes

...
