#!/bin/bash

readonly script_path="$(realpath "${0}")"
readonly script_dir="$(dirname "${script_path}")"

sudo apt-get --yes update

# For some reason, Debian's virtualenv package contains only
# The documentation and not the virtualen binary. All other
# tools using virtualenv will crash without python3-virtualenv
# package which actually includes virtualenv.
sudo apt-get --yes --no-install-recommends install \
    python3-pip                                    \
    python3-virtualenv                             \
    virtualenv                                     \
    virtualenvwrapper                              \
    git                                            \
    vim

sudo apt-get clean

export WORKON_HOME=~/.envs

if [[ -f "/usr/share/virtualenvwrapper/virtualenvwrapper.sh" ]]; then
    . "/usr/share/virtualenvwrapper/virtualenvwrapper.sh"
fi

mkvirtualenv --python=python3 -r "${script_dir}/ansible_requirements.txt" ansible

# software-properties-common  \
# firmware-misc-nonfree       \
# firmware-realtek            \
# firmware-iwlwifi            \
# ansible-lint                \
# ansible                     \
# python3-distutils           \
# r8168-dkms                  \
