#!/bin/bash

sudo apt-get update
sudo apt-get install software-properties-common git vim
sudo apt-add-repository --yes --update ppa:ansible/ansible
sudo apt-get --no-install-recommends install ansible

