---

- name: "create .vim directory structure"
  file:
    path: "{{ ansible_env.HOME }}/.vim/{{ item }}"
    state: "directory"
  loop:
    - "colors"
    - "plugin"

- name: "download the distinguished colorscheme"
  get_url:
    url: "https://raw.githubusercontent.com/Lokaltog/vim-distinguished/develop/colors/distinguished.vim"
    dest: "{{ ansible_env.HOME }}/.vim/colors/distinguished.vim"
    mode: "0644"

- name: "clone gruvbox colorscheme"
  git:
    repo: "https://github.com/morhetz/gruvbox.git"
    dest: "{{ ansible_env.HOME }}/.vim/pack/default/start/gruvbox"

- name: "download the vim-lastplace plugin"
  get_url:
    url: "https://raw.githubusercontent.com/farmergreg/vim-lastplace/master/plugin/vim-lastplace.vim"
    dest: "{{ ansible_env.HOME }}/.vim/plugin/lastplace.vim"
    mode: "0644"

- name: "copy .vimrc"
  copy:
    src: "vimrc"
    dest: "{{ ansible_env.HOME }}/.vimrc"

- name: "copy templates to the templates directory"
  become: "yes"
  copy:
    src: "templates"
    dest: "{{ ansible_env.HOME }}/.vim/"
    owner: "{{ ansible_env.USER }}"
    group: "{{ ansible_env.USER }}"

- name: "copy Vim configuration for root"
  become: "yes"
  copy:
    remote_src: "yes"
    src: "{{ ansible_env.HOME }}/{{ item }}"
    dest: "/root/"
  loop:
    - ".vim"
    - ".vimrc"

...
