---


- name: "create .vim directory structure"
  ansible.builtin.file:
    path: "{{ ansible_env.HOME }}/.vim/{{ item }}"
    state: "directory"
  loop:
    - "colors"
    - "plugin"


- name: "download the distinguished colorscheme"
  ansible.builtin.get_url:
    url: "https://raw.githubusercontent.com/Lokaltog/vim-distinguished/develop/colors/distinguished.vim"
    dest: "{{ ansible_env.HOME }}/.vim/colors/distinguished.vim"
    mode: "0644"


- name: "clone gruvbox colorscheme"
  ansible.builtin.git:
    repo: "https://github.com/morhetz/gruvbox.git"
    dest: "{{ ansible_env.HOME }}/.vim/pack/default/start/gruvbox"


- name: "clone nginx syntax"
  ansible.builtin.git:
    repo: "https://github.com/chr4/nginx.vim.git"
    dest: "{{ ansible_env.HOME }}/.vim/pack/default/start/nginx"


- name: "download the vim-lastplace plugin"
  ansible.builtin.get_url:
    url: "https://raw.githubusercontent.com/farmergreg/vim-lastplace/master/plugin/vim-lastplace.vim"
    dest: "{{ ansible_env.HOME }}/.vim/plugin/lastplace.vim"
    mode: "0644"


- name: "download the indentLine plugin"
  ansible.builtin.get_url:
    url: "https://raw.githubusercontent.com/Yggdroot/indentLine/master/after/plugin/indentLine.vim"
    dest: "{{ ansible_env.HOME }}/.vim/plugin/indentline.vim"
    mode: "0644"


- name: "copy .vimrc"
  ansible.builtin.copy:
    src: "vimrc"
    dest: "{{ ansible_env.HOME }}/.vimrc"
    owner: "{{ ansible_env.USER }}"
    group: "{{ ansible_env.USER }}"


- name: "copy Vim templates"
  become: "yes"
  ansible.builtin.copy:
    src: "templates"
    dest: "{{ ansible_env.HOME }}/.vim/"
    owner: "{{ ansible_env.USER }}"
    group: "{{ ansible_env.USER }}"


- name: "copy Vim configuration for root"
  become: "yes"
  ansible.builtin.copy:
    remote_src: "yes"
    src: "{{ ansible_env.HOME }}/{{ item }}"
    dest: "/root/"
  loop:
    - ".vim"
    - ".vimrc"


...
