---

- name: "download Nitrokey Application"
  get_url:
      url: "{{ nitrokey_url }}"
      dest: "{{ nitrokey_dir }}/{{ nitrokey_app }}"
      owner: "root"
      group: "root"
      mode: "0755"

- name: "copy Nitrokey App icons"
  copy:
      src: "hicolor"
      dest: "/usr/local/share/icons/"
      owner: "root"
      group: "root"

- name: "install menu entry"
  template:
      src: "nitrokey_app.desktop"
      dest: "/usr/local/share/applications/"
      owner: "root"
      group: "root"
      mode: "0644"

...
