---

- name: "copy firewall script to NetworManager's dispatcher"
  copy:
    src: "firewall"
    dest: "/etc/NetworkManager/dispatcher.d/pre-up.d/firewall"
    owner: "root"
    group: "root"
    mode: 0750

...
