---


- name: "copy firewall"
  ansible.builtin.copy:
    src: "nftables.conf"
    dest: "/etc/nftables.conf"
    owner: "root"
    group: "root"
    mode: "0750"


- name: "enable nftables"
  ansible.builtin.systemd:
    name: "nftables.service"
    state: "restarted"
    enabled: "yes"


...
