#!/usr/bin/env bash

set -o errexit
set -o nounset
set -x

# Flush all configuration.
iptables  -F
iptables  -X
iptables  -t nat -F
iptables  -t nat -X
iptables  -t mangle -F
iptables  -t mangle -X
iptables  -t raw -F
iptables  -t raw -X
iptables  -t security -F
iptables  -t security -X
ip6tables -F
ip6tables -X
ip6tables -t nat -F
ip6tables -t nat -X
ip6tables -t mangle -F
ip6tables -t mangle -X
ip6tables -t raw -F
ip6tables -t raw -X
ip6tables -t security -F
ip6tables -t security -X

# Default policies.
iptables  -P INPUT   DROP
iptables  -P FORWARD DROP
iptables  -P OUTPUT  ACCEPT
ip6tables -P INPUT   DROP
ip6tables -P FORWARD DROP
ip6tables -P OUTPUT  ACCEPT

# ESTABLISHED i RELATED.
iptables  -A INPUT -m conntrack --ctstate ESTABLISHED,RELATED -j ACCEPT
ip6tables -A INPUT -m conntrack --ctstate ESTABLISHED,RELATED -j ACCEPT

# Localhost.
iptables  -A INPUT -i lo -j ACCEPT
ip6tables -A INPUT -i lo -j ACCEPT

#  _____
# < SSH >
#  -----
#         \   ^__^             
#          \  (oo)\_______     
#             (__)\       )\/\ 
#                 ||----w |    
#                 ||     ||    
#                              
# fail2ban should be present.
iptables  -t filter -A INPUT -m conntrack --ctstate NEW -p tcp --dport 22 -j ACCEPT
ip6tables -t filter -A INPUT -m conntrack --ctstate NEW -p tcp --dport 22 -j ACCEPT
